#!/bin/bash -e

# -------------------------------------------------------------------------------------------------
# Functions
# -------------------------------------------------------------------------------------------------
BASEDIR=$(dirname $(readlink -f ${0}))
source "${BASEDIR}/util.sh"

function usage {
  echo "Remove the files from stage. The files shall be deleted permanently."
  echo "Usage: ${0} <file1> [<file2> <file3> ... <fileN>]"
  exit 0
}

# -------------------------------------------------------------------------------------------------
# Parse Arg
# -------------------------------------------------------------------------------------------------
if [[ ${#} -eq 1 && ("${1}" == "-h" || "${1}" == "--help") ]]
then
  usage
fi

if [[ ${#} -eq 0 ]]
then
  dieUsage "Incorrect argument count ${#}"
fi

pathToFile="${1}"

# -------------------------------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------------------------------
list=$(git-ls-stage-files)
if [[ ! "${list}" =~ "${pathToFile}" ]]
then
  echo "File '${pathToFile}' is not staged."
  exit 0
fi
git rm --cached --force --quiet -- ${@}